mybatis.data.source.driver=com.mysql.cj.jdbc.Driver
mybatis.data.source.url=jdbc:mysql://localhost:3306/spring_class
mybatis.data.source.user=root
mybatis.data.source.password=1234
mybatis.data.source.mybatisconfig=mybatis-config.xml
mybatis.data.source.aliases=com.hyw.mytest.entity